# Generated by Django 5.0.1 on 2024-02-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0002_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='numero_sensor',
            new_name='sensor_departamento',
        ),
    ]
