# Generated by Django 5.0.1 on 2024-02-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0004_piso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('numero_pisos', models.IntegerField()),
            ],
        ),
    ]
