# Generated by Django 5.0.1 on 2024-02-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0010_alter_piso_edificio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piso',
            old_name='edificio',
            new_name='edificio_id',
        ),
    ]
