# Generated by Django 5.0.1 on 2024-02-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0011_rename_edificio_piso_edificio_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
