# Generated by Django 5.0.1 on 2024-02-23 16:46

import Edificio.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0012_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='edificio_id',
            field=models.ForeignKey(default=Edificio.models.Edificio, on_delete=django.db.models.deletion.CASCADE, to='Edificio.edificio'),
        ),
    ]
