# Generated by Django 5.0.1 on 2024-02-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edificio', '0013_alter_piso_edificio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piso',
            old_name='edificio_id',
            new_name='edificio',
        ),
    ]
