# Generated by Django 5.0.1 on 2024-02-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('numero_pisos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_sensor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pisos', to='Repetix.edificio')),
            ],
        ),
    ]
