# Generated by Django 5.0.1 on 2024-03-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('numero_pisos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.PositiveIntegerField()),
                ('consumo_anterior', models.FloatField()),
                ('consumo_actual', models.FloatField()),
                ('consumo_sensor', models.FloatField()),
            ],
        ),
    ]
